name: Merval a Telegram

on:
  schedule:
    # Se ejecuta todos los días a las 12:00 y 15:00 hs de Argentina
    # Solo de lunes (1) a viernes (5)
    - cron: '0 15 * * 1-5'  # 12:00 ARG
    - cron: '0 18 * * 1-5'  # 15:00 ARG
  workflow_dispatch:  # Permite ejecución manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Python 3.10
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias necesarias
      - name: Instalar dependencias
        run: pip install requests yfinance pandas numpy matplotlib

      # 4️⃣ Ejecutar el script de Merval
      - name: Ejecutar mi_script.py
        run: python mi_script.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
